version: '2'
services:
    protractortechdemo-app:
        image: protractortechdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://protractortechdemo-mysql:3306/protractortechdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    protractortechdemo-mysql:
        extends:
            file: mysql.yml
            service: protractortechdemo-mysql
